import Head from 'next/head'
import { Inter } from '@next/font/google'
import axios from 'axios'
import { GetServerSideProps } from 'next'
import { useRouter } from 'next/router'
import { Movie } from '@/components/Movie'
import { MovieGrid } from '@/components/MovieGrid'
import { Pagination } from '@/components/Pagination'
import { Sidebar } from '@/components/Sidebar/Sidebar'

const inter = Inter({ subsets: ['latin'] })

interface IMovieData {
  id: number;
  title: string;
  original_title: string;
  language: string;
  overview: string;
  poster_path: string;
  release_date: string;
  vote_average: number;
  vote_count: number;
}

interface IRequest {
  results: IMovieData[],
  total_pages: number
}

export default function Home({results, total_pages}: IRequest) {
  const router = useRouter();
  
  return (
    <>
      <Head>
        <title>Movie.io</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full flex">
        <Sidebar />

        <div className='flex flex-col items-center w-full p-20'>
          <MovieGrid title='Popular movies'>
            {results.map((movie, index) => (
              <Movie key={movie.id + movie.title} movie={movie} />
            ))}
          </MovieGrid>
          
          <Pagination total_pages={total_pages} />
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({query}) => {
  const {page} = query
  
  const {data} = await axios.get<IRequest>(`https://api.themoviedb.org/3/movie/popular?language=pt-Br&page=${page ? page : 1}`, {
    headers: {
      Authorization: `Bearer ${process.env.TMDB_TOKEN_V4}`
    }
  });

  return {
    props: data
  }
}
